// @flow

export const CHANGE_MODE: string = 'chrome/CHANGE_MODE'
export const SIGNIN: string = 'chrome/SIGNIN'
export const SIGNIN_REQUEST: string = 'chrome/SIGNIN_REQUEST'
export const SIGNIN_SUCCESS: string = 'chrome/SIGNIN_SUCCESS'
export const SIGNIN_FAILURE: string = 'chrome/SIGNIN_FAILURE'
export const SIGNOUT: string = 'chrome/SIGNOUT'
export const SET_FLASH: string = 'chrome/SET_FLASH'
export const CLEAR_FLASH: string = 'chrome/CLEAR_FLASH'
export const TOGGLE_DRAWER: string = 'chrome/TOGGLE_DRAWER'
export const CHOOSE_APP: string = 'chrome/CHOOSE_APP'
export const CHOOSE_ITEM: string = 'chrome/CHOOSE_ITEM'
export const PUSH_NOTIFICATION: string = 'chrome/PUSH_NOTIFICATION'
export const READ_NOTIFICATION: string = 'chrome/READ_NOTIFICATION'
export const BEGIN_SEARCH: string = 'chrome/BEGIN_SEARCH'
export const ABORT_SEARCH: string = 'chrome/ABORT_SEARCH'
export const COMPLETE_SEARCH: string = 'chrome/COMPLETE_SEARCH'
export const LOOKUP: string = 'chrome/LOOKUP'
